ServiceHost/Areas/Administration/Pages/Accounts/Index.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Framework.Application;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Accounts
{
    public class IndexModel : PageModel
    {
        private readonly IAccountApplication accountApplication;
        private readonly IRoleApplication roleApplication;
        public AccountSearchModel SearchModel { get; set; }
        public List<AccountViewModel> Items { get; set; }
        public List<RoleViewModel> Roles { get; set; }

        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            this.accountApplication = accountApplication;
            this.roleApplication = roleApplication;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            SearchModel = searchModel;
            Items = accountApplication.Search(SearchModel);
            Roles = roleApplication.Search("");
        }
        public PartialViewResult OnGetCreate()
        {
            var result = new CreateAccount
            {
                Roles = roleApplication.Search("")
            };
            return Partial("./Create", result);
        }
        public PartialViewResult OnGetEdit(long id)
        {
            var result = accountApplication.EditGet(id);
            result.Roles = roleApplication.Search("");
            return Partial("./Edit", result);
        }
        public PartialViewResult OnGetChangePassword(long id)
        {
            return Partial("./ChangePassword", new ChangePassword() { Id = id });
        }
        public JsonResult OnPostCreate(CreateAccount command)
        {
            if (ModelState.IsValid)
                return new JsonResult(accountApplication.Create(command));
            return new JsonResult(ValidationMessages.InvalidModelStateMessage);
        }
        public JsonResult OnPostEdit(EditAccount command)
        {
            if (ModelState.IsValid)
                return new JsonResult(accountApplication.Edit(command));
            return new JsonResult(ValidationMessages.InvalidModelStateMessage);
        }
        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            if (ModelState.IsValid)
                return new JsonResult(accountApplication.ChangePassword(command));
            return new JsonResult(ValidationMessages.InvalidModelStateMessage);
        }
    }
}

ServiceHost/Areas/Administration/Pages/Shop/ProductCategories/Index.cshtml.cs
using Framework.Application;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductCategory;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductCategories
{
    public class IndexModel : PageModel
    {
        private readonly IProductCategoryApplication productCategoryApplication;
        public List<ProductCategoryMinimalViewModel> Items { get; set; }
        public SearchProductCategoy SearchModel { get; set; }


        public IndexModel(IProductCategoryApplication productCategoryApplication)
        {

            this.productCategoryApplication = productCategoryApplication;
        }


        public void OnGet(SearchProductCategoy command)
        {
            SearchModel = command;
            Items = productCategoryApplication.Search(SearchModel);
        }
        public PartialViewResult OnGetCreate()
        {
            return Partial("./Create", new CreateProductCategory());
        }
        public PartialViewResult OnGetEdit(long id)
        {
            var item = productCategoryApplication.EditGet(id);
            if (item != null)
                return Partial("./Edit", item);
            return null;

        }
        public JsonResult OnPostCreate(CreateProductCategory form)
        {
            if (ModelState.IsValid)
                return new JsonResult(productCategoryApplication.Create(form));
            else
            {
                OperationResult operation = new();
                return new JsonResult(operation.Failed(ValidationMessages.InvalidModelStateMessage));
            }
        }
        public JsonResult OnPostEdit(EditProductCategory form)
        {
            if (ModelState.IsValid)
            {
                return new JsonResult(productCategoryApplication.Edit(form));
            }
            else
            {
                OperationResult operation = new();
                return new JsonResult(operation.Failed(ValidationMessages.InvalidModelStateMessage));
            }
        }
        public IActionResult OnGetDelete(long id)
        {
            var operation = new OperationResult();
            var item = productCategoryApplication.Get(id);
            if (item != null)
                return Partial("Delete", id);
            return new JsonResult(operation.Failed(ApplicationMessages.NotFoundMessage));

        }
        public IActionResult OnPostDelete(long id)
        {
            return new JsonResult(productCategoryApplication.Delete(id));
        }
    }
}

ServiceHost/Areas/Administration/Pages/Shop/Products/Index.cshtml.cs
using Framework.Application;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Shop.Products
{
    public class IndexModel : PageModel
    {
        private readonly IProductApplication productApplication;
        private readonly IProductCategoryApplication productCategoryApplication;
        public List<ProductMinimalViewModel> Items { get; set; }
        public ProductSearchModel SearchModel { get; set; }
        public SelectList ProductCategories { get; set; }

        public IndexModel(IProductApplication productApplication, IProductCategoryApplication productCategoryApplication)
        {
            this.productApplication = productApplication;
            this.productCategoryApplication = productCategoryApplication;
        }


        public void OnGet(ProductSearchModel command)
        {
            SearchModel = command;
            Items = productApplication.Search(command);
            ProductCategories = new SelectList(productCategoryApplication.List(), "Id", "Name");
        }
        public PartialViewResult OnGetCreate()
        {
            var Form = new CreateProduct
            {
                Categories = productCategoryApplication.List()
            };
            return Partial("./Create", Form);
        }
        public PartialViewResult OnGetEdit(long id)
        {
            var item = productApplication.EditGet(id);
            item.Categories = productCategoryApplication.List();
            if (item != null)
                return Partial("./Edit", item);
            return null;

        }
        public JsonResult OnPostCreate(CreateProduct form)
        {
            if (ModelState.IsValid)
                return new JsonResult(productApplication.Create(form));
            OperationResult operation = new();
            return new JsonResult(operation.Failed(ValidationMessages.InvalidModelStateMessage));
        }
        public JsonResult OnPostEdit(EditProduct form)
        {
            if (ModelState.IsValid)
                return new JsonResult(productApplication.Edit(form));
            OperationResult operation = new();
            return new JsonResult(operation.Failed(ValidationMessages.InvalidModelStateMessage));
        }
        public IActionResult OnGetDelete(long id)
        {
            var operation = new OperationResult();
            var item = productApplication.Get(id);
            if (item != null)
                return Partial("Delete", id);
            return new JsonResult(operation.Failed(ApplicationMessages.NotFoundMessage));

        }
        public IActionResult OnPostDelete(long id)
        {
            return new JsonResult(productApplication.Delete(id));
        }
    }

}

ServiceHost/Pages/Account.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccountModel : PageModel
    {
        private readonly IAccountApplication accountApplication;

        public RegisterAccount RegisterAccount { get; set; }
        public Login Login { get; set; }


        [TempData]
        public string LoginMessage { get; set; }
        [TempData]
        public string RegisterMessage { get; set; }
        public AccountModel(IAccountApplication accountApplication)
        {
            this.accountApplication = accountApplication;
        }

        public void OnGet()
        {
        }
        public IActionResult OnPostLogin(Login login)
        {
            Login = login;
            if (ModelState.IsValid)
            {
                var result = accountApplication.Login(Login);
                LoginMessage = result.Message;
                if (result.IsSucceeded)
                    return RedirectToPage("/Index");
                else
                    return Page();
            }

            return Page();
        }
        public IActionResult OnPostRegister(RegisterAccount registerAccount)
        {
            RegisterAccount = registerAccount;
            if (ModelState.IsValid)
            {
                var result = accountApplication.Register(RegisterAccount);
                RegisterMessage = result.Message;
                if (result.IsSucceeded)
                    return RedirectToPage("/Index");
            }
            return Page();
        }

        public IActionResult OnGetLogout()
        {
            accountApplication.Logout();
            return RedirectToPage("/Index");
        }
    }
}

ServiceHost/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/Product.cshtml.cs
using LampshadeQuery.Contracts.Product;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class ProductModel : PageModel
    {
        private readonly IProductQuery productQuery;
        public ProductQueryModel Product { get; set; }
        public ProductModel(IProductQuery productQuery)
        {
            this.productQuery = productQuery;
        }

        public void OnGet(string name)
        {
            Product = productQuery.GetProductBySlug(name);
        }
    }
}

ServiceHost/Pages/ProductCategory.cshtml.cs
using LampshadeQuery.Contracts.ProductCategory;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class ProductCategoryModel : PageModel
    {
        private readonly IProductCategoryQuery productCategoryQuery;
        public ProductCategoryQueryModel ProductCategory { get; set; }
        public ProductCategoryModel(IProductCategoryQuery productCategoryQuery)
        {
            this.productCategoryQuery = productCategoryQuery;
        }

        public void OnGet(string name)
        {
            ProductCategory = productCategoryQuery.GetProductCategoryBySlug(name);
        }
    }
}

ServiceHost/Pages/Account.cshtml
@page
@model ServiceHost.Pages.AccountModel
@{
    ViewData["Title"] = "ورود به ناحیه کاربری";
}
<div class="breadcrumb-area section-space--half">
    <div class="container wide">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-wrapper breadcrumb-bg">
                    <div class="breadcrumb-content">
                        <h2 class="breadcrumb-content__title">ورود و ثبت نام</h2>
                        <ul class="breadcrumb-content__page-map">
                            <li><a asp-page="/Index">صفحه اصلی</a></li>
                            <li class="active">ورود - ثبت نام</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
                                @if (Model.LoginMessage != null)
                                {
                                    <div class="alert alert-danger">@Model.LoginMessage</div>
                                }
                                <form method="post" asp-page-handler="Login">
                                    <div class="login-form">
                                        <h4 class="login-title">ورود</h4>
                                        <div class="row">
                                            <div class="col-md-12 col-12">
                                                <label asp-for="Login.Username">نام کاربری</label>
                                                <input type="text"  asp-for="Login.Username" placeholder="نام کاربری">
                                                <span asp-validation-for="Login.Username"></span>
                                            </div>
                                            <div class="col-12">
                                                <label asp-for="Login.Password">کلمه عبور</label>
                                                <input type="password" asp-for="Login.Password" placeholder="کلمه عبور">
                                                <span asp-validation-for="Login.Password"></span>
                                            </div>

                                            @*<div class="col-sm-6">
                                                    <div class="check-box d-inline-block ml-0 ml-md-2">
                                                        <input type="checkbox" id="remember_me">
                                                        <label for="remember_me">Remember me</label>
                                                    </div>
                                                </div>*@

                                            <div class="col-sm-6 text-left text-sm-right">
                                                <a href="#" class="forget-pass-link">رمز عبور را فراموش کرده اید؟</a>
                                            </div>

                                            <div class="col-md-12">
                                                <button class="register-button">ورود</button>
                                            </div>

                                        </div>
                                    </div>

                                </form>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12">
                                @if (Model.RegisterMessage != null)
                                {
                                    <div class="alert alert-danger">@Model.RegisterMessage</div>
                                }
                                <form method="post" asp-page="./Account" asp-page-handler="Register">
                                    <div class="login-form">
                                        <h4 class="login-title">ثبت نام</h4>
                                        <div class="row">
                                            <div class="col-md-6 col-12 mb-20">
                                                <label asp-for="RegisterAccount.FullName">نام کامل</label>
                                                <input type="text" asp-for="RegisterAccount.FullName" placeholder="نام کامل">
                                                <span class="text-danger" asp-validation-for="RegisterAccount!.FullName"></span>
                                            </div>
                                            <div class="col-md-6 col-12 mb-20">
                                                <label asp-for="RegisterAccount.Username">نام کاربری</label>
                                                <input type="text" asp-for="RegisterAccount.Username" placeholder="نام کاربری">
                                                <span class="text-danger" asp-validation-for="RegisterAccount.Username"></span>
                                            </div>
                                            <div class="col-md-12 mb-20">
                                                <label asp-for="RegisterAccount.PhoneNumber">موبایل</label>
                                                <input type="tel" asp-for="RegisterAccount.PhoneNumber" placeholder="09123456789" >
                                                <span class="text-danger" asp-validation-for="RegisterAccount.PhoneNumber"></span>
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label asp-for="RegisterAccount.Password"> کلمه عبور</label>
                                                <input type="password" asp-for="RegisterAccount.Password"  placeholder="کلمه عبور">
                                                <span class="text-danger" asp-validation-for="RegisterAccount.Password"></span>
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label asp-for="RegisterAccount.ConfirmPassword">تایید کلمه عبور</label>
                                                <input type="password" asp-for="RegisterAccount.ConfirmPassword" placeholder=" تایید کلمه عبور">
                                                <span class="text-danger" asp-validation-for="RegisterAccount.ConfirmPassword"></span>
                                            </div>
                                            <div class="col-12">
                                                <button type="submit" class="register-button mt-0">ثبت نام</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ServiceHost/Pages/ProductCategory.cshtml
@page "{name}"
@model ServiceHost.Pages.ProductCategoryModel
@{
    ViewData["Title"] = "دسته بندی محصولات";
}

    <div class="breadcrumb-area section-space--half">
        <div class="container wide">
            <div class="row">
                <div class="col-lg-12">
                    <!--=======  breadcrumb wrpapper  =======-->
                    <div class="breadcrumb-wrapper breadcrumb-bg">
                        <!--=======  breadcrumb content  =======-->
                        <div class="breadcrumb-content">
                            <h2 class="breadcrumb-content__title">مشاهده محصولات دسته بندی</h2>
                            <ul class="breadcrumb-content__page-map">
                                <li><a asp-page="Index">خانه</a></li>
                                <li class="active">
                                @Model.ProductCategory.Name
                            </li>
                            </ul>
                        </div>
                        <!--=======  End of breadcrumb content  =======-->
                    </div>
                    <!--=======  End of breadcrumb wrpapper  =======-->
                </div>
            </div>
        </div>
    </div>
    <!--====================  End of breadcrumb area  ====================-->
    <div class="page-content-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!--=======  shop page wrapper  =======-->
                    <div class="page-wrapper">
                        <div class="page-content-wrapper">
                            <div class="row">
                                <div class="col-lg-12">
                                    <!--=======  shop page header  =======-->
@*                                    <div class="shop-header">
                                        <div class="shop-header__left">
                                            <div class="shop-header__left__message">
                                                Showing 1 to 9 of 15 (2 Pages)
                                            </div>
                                        </div>

                                        <div class="shop-header__right">

                                            <div class="single-select-block d-inline-block">
                                                <span class="select-title">Show:</span>
                                                <select>
                                                    <option value="1">10</option>
                                                    <option value="2">20</option>
                                                    <option value="3">30</option>
                                                    <option value="4">40</option>
                                                </select>
                                            </div>

                                            <div class="single-select-block d-inline-block">
                                                <span class="select-title">Sort By:</span>
                                                <select class="pr-0">
                                                    <option value="1">Default</option>
                                                    <option value="2">Name (A-Z)</option>
                                                    <option value="3">Price (min - max)</option>
                                                    <option value="4">Color</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>*@
                                    <!--=======  End of shop page header  =======-->
                                </div>

                                <div class="col-lg-12">
                                    <!--=======  shop page content  =======-->
                                    <div class="shop-page-content">

                                        <div class="row shop-product-wrap grid three-column">
                                            @foreach(var product in Model.ProductCategory.Products)
                                            {
                                            <div class="col-12 col-lg-4 col-md-4 col-sm-6">
                                                <!--=======  product grid view  =======-->
                                                <div class="single-grid-product grid-view-product">
                                                    <div class="single-grid-product__image">
                                                        @if (product.DiscountPercentage != 0)
                                                        {
                                                            <div class="single-grid-product__label">
                                                                <span class="sale">@product.DiscountPercentage%-</span>
                                                            </div>
                                                        }
                                                        <a asp-page="/Product" asp-route-name="@product.Slug">
                                                            <img src="~/Uploads/Product/@product.Picture" class="img-fluid"
                                                                 alt="">

                                                        </a>

                                                        <div class="hover-icons">
                                                            <a href="javascript:void(0)">
                                                                <i class="ion-bag"></i>
                                                            </a>
                                                            <a href="javascript:void(0)" data-toggle="modal"
                                                               data-target="#quick-view-modal-container">
                                                                <i class="ion-android-open"></i>
                                                            </a>
                                                        </div>
                                                    </div>
                                                    <div class="single-grid-product__content">
                                                        <div class="single-grid-product__category-rating">
                                                            <span class="category">
                                                                <a asp-page="/Product" asp-route-name="@product.Slug">@product.Name</a>
                                                            </span>
@*                                                            <span class="rating">
                                                                <i class="ion-android-star active"></i>
                                                                <i class="ion-android-star active"></i>
                                                                <i class="ion-android-star active"></i>
                                                                <i class="ion-android-star active"></i>
                                                                <i class="ion-android-star-outline"></i>
                                                            </span>*@
                                                        </div>

                                                        <h3 class="single-grid-product__title">
                                                            <a asp-page="/ProductDetails">@product.Description
                                                            </a>
                                                        </h3>
                                                        <p class="single-grid-product__price">
                                                            @if (product.Price <= 0 || product.Quantity <= 0)
                                                            {
                                                                <span class="main-price">ناموجود</span>

                                                            }
                                                            else if (product.DiscountPercentage != 0)
                                                            {
                                                                <span class="main-price discounted">@product.BasePriceUI تومان</span>
                                                                <br />
                                                                <span class="discounted-price">@product.FinalPriceUI تومان</span>
                                                            }
                                                            else
                                                            {
                                                                <span class="main-price">@product.BasePriceUI تومان</span>
                                                            }
                                                        </p>
                                                        @if(product.DiscountPercentage != 0 && product.Price > 0 )
                                                        {
                                                            <div class="product-countdown" data-countdown="@product.DiscountEndDate"></div>

                                                        }

                                                    </div>
                                                </div>
                                                <!--=======  End of product grid view  =======-->

                                            </div>
                                            }

                                        </div>

                                    </div>

                                    <!--=======  pagination area =======-->
                                   @* <div class="pagination-area">
                                        <div class="pagination-area__left">
                                            Showing 1 to 9 of 11 (2 Pages)
                                        </div>
                                        <div class="pagination-area__right">
                                            <ul class="pagination-section">
                                                <li>
                                                    <a class="active" href="#">1</a>
                                                </li>
                                                <li>
                                                    <a href="#">2</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>*@
                                    <!--=======  End of pagination area  =======-->
                                    <!--=======  End of shop page content  =======-->
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--=======  End of shop page wrapper  =======-->
                </div>
            </div>
        </div>
    </div>