ServiceHost/Areas/Administration/Pages/Accounts/Index.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Framework.Application;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Accounts
{
    public class IndexModel : PageModel
    {
        private readonly IAccountApplication accountApplication;
        private readonly IRoleApplication roleApplication;
        public AccountSearchModel SearchModel { get; set; }
        public List<AccountViewModel> Items { get; set; }
        public List<RoleViewModel> Roles { get; set; }

        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            this.accountApplication = accountApplication;
            this.roleApplication = roleApplication;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            SearchModel = searchModel;
            Items = accountApplication.Search(SearchModel);
            Roles = roleApplication.Search("");
        }
        public PartialViewResult OnGetCreate()
        {
            var result = new CreateAccount
            {
                Roles = roleApplication.Search("")
            };
            return Partial("./Create", result);
        }
        public PartialViewResult OnGetEdit(long id)
        {
            var result = accountApplication.EditGet(id);
            result.Roles = roleApplication.Search("");
            return Partial("./Edit", result);
        }
        public PartialViewResult OnGetChangePassword(long id)
        {
            return Partial("./ChangePassword", new ChangePassword() { Id = id });
        }
        public JsonResult OnPostCreate(CreateAccount command)
        {
            if (ModelState.IsValid)
                return new JsonResult(accountApplication.Create(command));
            return new JsonResult(ValidationMessages.InvalidModelStateMessage);
        }
        public JsonResult OnPostEdit(EditAccount command)
        {
            if (ModelState.IsValid)
                return new JsonResult(accountApplication.Edit(command));
            return new JsonResult(ValidationMessages.InvalidModelStateMessage);
        }
        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            if (ModelState.IsValid)
                return new JsonResult(accountApplication.ChangePassword(command));
            return new JsonResult(ValidationMessages.InvalidModelStateMessage);
        }
    }
}

ServiceHost/Pages/Account.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccountModel : PageModel
    {
        private readonly IAccountApplication accountApplication;

        public RegisterAccount RegisterAccount { get; set; }
        public Login Login { get; set; }


        [TempData]
        public string LoginMessage { get; set; }
        [TempData]
        public string RegisterMessage { get; set; }
        public AccountModel(IAccountApplication accountApplication)
        {
            this.accountApplication = accountApplication;
        }

        public void OnGet()
        {
        }
        public IActionResult OnPostLogin(Login login)
        {
            Login = login;
            if (ModelState.IsValid)
            {
                var result = accountApplication.Login(Login);
                LoginMessage = result.Message;
                if (result.IsSucceeded)
                    return RedirectToPage("/Index");
                else
                    return Page();
            }

            return Page();
        }
        public IActionResult OnPostRegister(RegisterAccount registerAccount)
        {
            RegisterAccount = registerAccount;
            if (ModelState.IsValid)
            {
                var result = accountApplication.Register(RegisterAccount);
                RegisterMessage = result.Message;
                if (result.IsSucceeded)
                    return RedirectToPage("/Index");
            }
            return Page();
        }

        public IActionResult OnGetLogout()
        {
            accountApplication.Logout();
            return RedirectToPage("/Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/ChangePassword.cshtml
@model AccountManagement.Application.Contracts.Account.ChangePassword;

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title">تغییر رمز عبور</h5>
            </div>
            <div id="modal-body" class="modal-body">
                <form class="form-group" method="post" asp-page="./Index" asp-page-handler="ChangePassword"
                      data-ajax="true"
                      data-action="refresh">
                    <div class="row">

                        <div class="col-md-6">
                            <label class="control-label" asp-for="@Model.Password">رمز عبور</label>
                            <input class="form-control" asp-for="@Model.Password" type="password" />
                            <span asp-validation-for="@Model.Password" class="text-danger"></span>
                        </div>

                        <div class="col-md-6">
                            <label class="control-label" asp-for="@Model.RepeatedPassword">تکرار رمز عبور</label>
                            <input class="form-control" asp-for="@Model.RepeatedPassword" type="password" />
                            <span asp-validation-for="@Model.RepeatedPassword" class="text-danger"></span>
                        </div>
                        <input type="hidden" asp-for="@Model.Id" value="@Model.Id" />
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                        <button type="submit" class="btn btn-primary">ثبت</button>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>

ServiceHost/Areas/Administration/Pages/Accounts/Create.cshtml
@model AccountManagement.Application.Contracts.Account.CreateAccount;

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title">ایجاد حساب جدید</h5>
            </div>
            <div id="modal-body" class="modal-body">
                <form class="form-group" method="post" asp-page="./Index" asp-page-handler="Create"
                      data-ajax="true"
                      data-action="refresh">
                    <div class="row">

                        <div class="col-md-6">

                            <label class="control-label" asp-for="@Model.FullName">نام و نام خانوادگی</label>
                            <input class="form-control" asp-for="@Model.FullName" type="text" />
                            <span asp-validation-for="@Model.FullName" class="text-danger"></span>
                        </div>

                        <div class="col-md-6">

                            <label class="control-label" asp-for="@Model.PhoneNumber">شماره تلفن همراه</label>
                            <input class="form-control" asp-for="@Model.PhoneNumber" type="tel" />
                            <span asp-validation-for="@Model.PhoneNumber" class="text-danger"></span>

                        </div>
                        <div class="col-md-6">

                            <label class="control-label" asp-for="@Model.RoleId">نقش کاربر</label>
                            <select class="form-control" asp-for="@Model.RoleId"  asp-items='new SelectList(Model.Roles,"Id","Name")'>
                                <option value="0">انتخاب نقش کاربر</option>
                            </select>
                            <span asp-validation-for="@Model.RoleId" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">

                            <label class="control-label" asp-for="@Model.Username">نام کاربری</label>
                            <input class="form-control" asp-for="@Model.Username" type="text" />
                            <span asp-validation-for="@Model.Username" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">

                            <label class="control-label" asp-for="@Model.Password">رمز عبور</label>
                            <input class="form-control" asp-for="@Model.Password" type="password" />
                            <span asp-validation-for="@Model.Password" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">

                            <label class="control-label" asp-for="@Model.ConfirmPassword">تکرار رمز عبور</label>
                            <input class="form-control" asp-for="@Model.ConfirmPassword" type="password" />
                            <span asp-validation-for="@Model.ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                        <button type="submit" class="btn btn-primary">ایجاد</button>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>

ServiceHost/Areas/Administration/Pages/Accounts/Edit.cshtml
@model AccountManagement.Application.Contracts.Account.EditAccount;

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title">ویرایش حساب</h5>
            </div>
            <div id="modal-body" class="modal-body">
                <form class="form-group" method="post" asp-page="./Index" asp-page-handler="Edit"
                      data-ajax="true"
                      data-action="refresh">
                    <div class="row">

                        <div class="col-md-6">

                            <label class="control-label" asp-for="@Model.FullName">نام و نام خانوادگی</label>
                            <input class="form-control" asp-for="@Model.FullName" type="text" />
                            <span asp-validation-for="@Model.FullName" class="text-danger"></span>
                        </div>

                        <div class="col-md-6">

                            <label class="control-label" asp-for="@Model.PhoneNumber">شماره تلفن همراه</label>
                            <input class="form-control" asp-for="@Model.PhoneNumber" type="tel" />
                            <span asp-validation-for="@Model.PhoneNumber" class="text-danger"></span>

                        </div>

                        <div class="col-md-6">

                            <label class="control-label" asp-for="@Model.RoleId">نقش کاربر</label>
                            <select class="form-control" asp-for="@Model.RoleId" asp-items='new SelectList(Model.Roles,"Id","Name")'>
                                <option value="0">انتخاب نقش کاربر</option>
                            </select>
                            <span asp-validation-for="@Model.RoleId" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">

                            <label class="control-label" asp-for="@Model.Username">نام کاربری</label>
                            <input class="form-control" asp-for="@Model.Username" type="text" />
                            <span asp-validation-for="@Model.Username" class="text-danger"></span>
                        </div>
                    </div>
                    <input type="hidden" asp-for="@Model.Id" value="@Model.Id" />
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                        <button type="submit" class="btn btn-primary">ویرایش</button>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>

ServiceHost/Areas/Administration/Pages/Accounts/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.Accounts.IndexModel
@{
    ViewData["Title"] = "حساب ها";
}
<link rel="stylesheet" href="~/AdminTheme/assets/datatables/jquery.dataTables.min.css" />

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در تخفیف ها</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="control-label" asp-for="@Model.SearchModel.RoleId">نقش کاربر</label>
                        <select class="form-control" asp-for="@Model.SearchModel.RoleId" asp-items='new SelectList(Model.Roles,"Id","Name")'>
                            <option value="0">انتخاب نقش کاربر</option>
                        </select>
                        <span asp-validation-for="@Model.SearchModel.RoleId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="@Model.SearchModel.Name"></label>
                        <input type="text" class="form-control" placeholder="نام یا نام خانوادگی" asp-for="@Model.SearchModel.Name" />

                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="@Model.SearchModel.Username"></label>
                        <input type="text" class="form-control" placeholder="نام کاربری" asp-for="@Model.SearchModel.Username" />

                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="@Model.SearchModel.PhoneNumber"></label>
                        <input type="tel" class="form-control" placeholder="تلفن همراه" asp-for="@Model.SearchModel.PhoneNumber" />

                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="panel">
    <div class="panel-heading">
        <a class=" btn btn-success" href='#showmodal=@Url.Page("./Index","Create")'><i class="fa fa-plus"></i>&nbsp; ایجاد</a>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-striped" id="datatable">
            <thead>
                <tr>
                    <th>شناسه</th>
                    <th>عکس</th>
                    <th>نام</th>
                    <th>نام کاربری</th>
                    <th>شماره همراه</th>
                    <th>نقش</th>
                    <th>عملیات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Items)
                {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.ProfilePicture</td>
                    <td>@item.FullName</td>
                    <td>@item.Username</td>
                    <td>@item.PhoneNumber</td>
                    <td>@Model.Roles.FirstOrDefault(x=>x.Id == item.RoleId).Name</td>
                    <td>
                        <a class="btn tbn-sm btn-warning" href='#showmodal=@Url.Page("./Index","Edit",new { Id = item.Id})'>ویرایش</a>
                        <a class="btn tbn-sm btn-info" href='#showmodal=@Url.Page("./Index","ChangePassword",new { Id = item.Id})'>تغییر رمز عبور</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div id="modal-wrapper"></div>

@section Scripts
{
    <script src="~/AdminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Theme/assets/js/persian-date.min.js"></script>
    <script src="~/Theme/assets/js/persian-datepicker.min.js"></script>
    <script src="~/AdminTheme/assets/datatables/dataTables.bootstrap.js"></script>
    <script src="~/AdminTheme/assets/datatables/datatables.js"></script>
    <script>
        $(document).ready(function () {
            $("#datatable").DataTable();
            $(".persian-date-input").persianDatepicker({
                autoClose: true,
                format: "YYYY/MM/DD"
            });
        });
    </script>
}